#ifndef VERSIONCONTROL_GLOBAL_H
#define VERSIONCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VERSIONCONTROL_LIBRARY)
#  define VERSIONCONTROLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VERSIONCONTROLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VERSIONCONTROL_GLOBAL_H
