#include "makefilegenerator.h"
#include <compiler/compilersetting.h>
#include <core_constants.h>
#include <project.h>
#include <bases.h>
#include "buildvariables.h"


MakeFileGenerator::MakeFileGenerator(QObject *parent):
  QObject(parent)
{

}

QString MakeFileGenerator::language()
{
  if(project->projectLanguage() == "CPP")
    return Core::Compiler::CXX;
  else
    return Core::Compiler::CC;
}


void MakeFileGenerator::setSetting(CompilerSetting * s)
{
  setting = s;
}

void MakeFileGenerator::setProject(Project * pro)
{
  project = pro;

  _buildVars->addVariable("PROJECTNAME",project->baseName());
  _buildVars->addVariable("PROJECTDIR",project->path());

  Config * config = project->currentConfiguration();
  _buildVars->addVariable("CONFIG",config->name());

  _buildVars->addVariable("DESTDIR",config->destDir());
  _buildVars->addVariable("TARGET",config->target());
  _buildVars->addVariable("DESTDIR_TARGET",config->destDirTarget());
  _buildVars->addVariable("OBJECTS_DIR",config->objectsOutputDir());

  _buildVars->fromList(config->stringList(Core::Project::BUILD_VARIABLES));
}

void MakeFileGenerator::setGlobalVariables(const QStringList &globalVariables)
{
  _buildVars->fromList(globalVariables);
}

void MakeFileGenerator::generateMakeFile()
{
  QString out;

  out +="#Makefile generated by SmartCode\n#Copyright (C) 2015 Achrouf corporation\n";

  out += Core::BuildManager::CC ;
  out += "=" ;
  out +=setting->toCC() + "\n";
  out += Core::BuildManager::CXX;
  out += "=" ;
  out += setting->toCXX()+ "\n";

  foreach(QString var, globalVars->projectVariables())
    {
      out += var;
      out += "= ";
      out += Bases::variant2String(globalVars->evaluateVariable(var));
      out += "\n";
    }

  out+="CCFLAGS= -g -Wall\n";
  out+="LDFLAGS=\n";
  out+="OBJ=";

  foreach(QString s,project->stringList(SOURCES)())
    {
      QString obj = s.replace(QFileInfo(s).suffix() , "o");

      out += " " ;

      if(!project->currentConfiguration()->objectsOutputDir().isEmpty())
        out += "$(OBJDIR)/";

      out+= obj;
    }

  out += "\n";
  out += "INCS= ";

  foreach(QString inc,setting->toCXXIncludes())
    {
      out += "-I\"" + inc+"\" "  ;
    }

  foreach(QString include,project->currentConfiguration()->includes())
    {
      out+="-I\"" + include+"\" "  ;
    }

  out+="\n";
  out+="LIBS= ";

  foreach(QString lib,setting->toLibs())
    {
      out+="-L\"" + lib+"\" "  ;
    }

  foreach(QString inclib,project->currentConfiguration()->includeLibs())
    {
      out+="-L\"" + inclib+"\" "  ;
    }

  foreach(QString lib,project->currentConfiguration()->libs())
    {
      out+=insertLib(lib) +" ";
    }

  out+="\n";
  out+="CXXFLAGS=$(INCS) -g -Wall";

  out+="\n";

  out+="all: $(DESTDIR_TARGET)\n";
  out+="$(DESTDIR_TARGET): $(OBJ)\n";

  switch(project->currentConfiguration()->toInt(Core::Project::TEMPLATE))
    {
    case Config::App:
      out+="\t$("+language()+") -o ";
      out+="$(DESTDIR_TARGET) $(OBJ) $(LIBS)\n";
      break;
    case Config::Lib:
      out+="\tar r $(DESTDIR_TARGET) $(OBJ)\n\tranlib $(DESTDIR_TARGET)";
      break;
    case Config::SharedLib:
      out+="\t$("+language()+") -shared -o ";
      out+="$(DESTDIR_TARGET) $(OBJ) $(LIBS)\n";
      break;
    }

  out +="\n";

  foreach(QString s,project->stringList(SOURCES)())
    {
      QString name=s;
      QString obj=s.replace(QFileInfo(s).suffix(),"o");

      QString com="\t$("+language()+")";
      QString arg="$("+language()+"FLAGS)";

      out += obj + ": " + name;
      out += "\n";
      out += com + " -c " + name + " -o " + obj + " " + arg;
      out += "\n";
    }

  out +=".PHONY: clean mrproper\nclean:\n\tdel -rf $(OBJ)\n mrproper: clean\n\tdel -rf $(DESTDIR_TARGET)\n";

  Bases::out(project->makeFile() ,out);
}

QString MakeFileGenerator::insertLib(const QString &lib)
{
  if(QFileInfo(lib).baseName().startsWith("lib"))
    return lib;
  else
    return "-l"+lib;
}
